export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import "../globals.css";

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
