function MetricsIcon() {
    return (
        <svg id="Layer_1" version="1.1" viewBox="0 0 128 128">
        <line
          fill="none"
          stroke="#00AEEF"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          strokeWidth="4"
          x1="32"
          x2="31"
          y1="65"
          y2="65"
        />
        <line
          fill="none"
          stroke="#00AEEF"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          strokeWidth="4"
          x1="99"
          x2="98"
          y1="65"
          y2="65"
        />
        <line
          fill="none"
          stroke="#00AEEF"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          strokeWidth="4"
          x1="36.4211617"
          x2="35.5551376"
          y1="48.5"
          y2="48"
        />
        <line
          fill="none"
          stroke="#00AEEF"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          strokeWidth="4"
          x1="48.5"
          x2="48"
          y1="36.4211617"
          y2="35.5551376"
        />
        <line
          fill="none"
          stroke="#00AEEF"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          strokeWidth="4"
          x1="93.5788345"
          x2="94.4448624"
          y1="48.5"
          y2="48"
        />
        <line
          fill="none"
          stroke="#00AEEF"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          strokeWidth="4"
          x1="81.5"
          x2="82"
          y1="36.4211617"
          y2="35.5551376"
        />
        <line
          fill="none"
          stroke="#00AEEF"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          strokeWidth="4"
          x1="65"
          x2="65"
          y1="32"
          y2="31"
        />
        <line
          fill="none"
          stroke="#00AEEF"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          strokeWidth="4"
          x1="73"
          x2="66.5840073"
          y1="45.0550575"
          y2="68.9998627"
        />
        <circle
          cx="65"
          cy="65"
          fill="none"
          r="44"
          stroke="#00AEEF"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          strokeWidth="4"
        />
        <line
          fill="none"
          stroke="#00AEEF"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          strokeWidth="4"
          x1="83"
          x2="106"
          y1="77"
          y2="77"
        />
        <line
          fill="none"
          stroke="#00AEEF"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          strokeWidth="4"
          x1="23"
          x2="47"
          y1="77"
          y2="77"
        />
        <circle
          cx="65"
          cy="77"
          fill="none"
          r="8"
          stroke="#00AEEF"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          strokeWidth="4"
        />
      </svg>
    )
}

export default MetricsIcon