"use client";

import { AuthProvider } from "@/features/auth/contexts/AuthContext";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Mulish } from "next/font/google";
import { useState } from "react";

const mulish = Mulish({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [queryClient] = useState(() => new QueryClient());

  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <body className={mulish.className}>
          <AuthProvider>{children}</AuthProvider>
        </body>
      </html>
    </QueryClientProvider>
  );
}
