"use client";

import "./globals.css";
import styles from "./utils.module.css";
import GmailTreeView from "./components/TreeView/NodesTreeView";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={`${styles.sidebar}`}>
          <GmailTreeView />
        </div>
        <div className={`${styles.content}`}>{children}</div>
      </body>
    </html>
  );
}
