"use client";

import GmailTreeView from "@/features/treeview/components/NodesTreeView";
import "../globals.css";
import styles from "../utils.module.css";
import { useAuth } from "@/features/auth/contexts/AuthContext";
import { useRouter } from "next/navigation";
import NavBar from "./NavBar";
import SideBar from "./sidebar/SideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  let auth = useAuth();

  return (
    <>
      <NavBar />
      <div className="homeContainer">
        <div className={`${styles.sidebar}`}>
          <SideBar />
        </div>
        <div className={`${styles.content}`}>{children}</div>
      </div>
    </>
  );
}
